const { config } = require("secreta");

const {
  SPREADSHEET_DOC_PROD,
  SHIPMENT_API_PROD,
  SMCOREAPIKEY_PROD,
  WAREHOUSE_APPID_PROD,
  WAREHOUSE_ACCESSTOKEN_PROD,
  APPSHEET_BASEURL,
  WAREHOUSE_APPID_TEST,
  WAREHOUSE_ACCESSTOKEN_TEST,
  SPREADSHEET_DOC_TEST,
  SHIPMENT_API_TEST,
  SMCOREAPIKEY_TEST,
} = config;
const SPREADSHEET_DOC = SPREADSHEET_DOC_PROD
const SHIPMENT_API = SHIPMENT_API_PROD;
const SMCOREAPIKEY = SMCOREAPIKEY_PROD;
const WAREHOUSE_APPID = WAREHOUSE_APPID_PROD;
const WAREHOUSE_ACCESSTOKEN = WAREHOUSE_ACCESSTOKEN_PROD;
const SMCOREHEADERS = {
  "Content-Type": "application/json",
  Authorization: `Bearer ${SMCOREAPIKEY}`,
};

module.exports = {
    APPSHEET_BASEURL,
    SPREADSHEET_DOC,
    SHIPMENT_API,
    WAREHOUSE_ACCESSTOKEN,
    WAREHOUSE_APPID,
    SMCOREHEADERS
}